# windowrule = workspace 1 silent,firefox
#windowrule = workspace 1, tag:"bg_firefox"

#exec-once = firefox --new-instance &
#exec-once = ~/.config/hypr/scripts/bg_firefox &

exec-once = hyprctl dispatch workspace 2
exec = ~/.config/hypr/cursor_center.sh
